### ISSUE TITLE
CT: Setting right is invalid when the node has invalid bounds

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/projectile-motion#165]
```
projectile-motion : xss-fuzz : load
Uncaught Error: Assertion failed: Setting right is invalid when the node has invalid (empty/NaN/infinite) bounds.
Error: Assertion failed: Setting right is invalid when the node has invalid (empty/NaN/infinite) bounds.
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1536838001842/assert/js/assert.js:22:13)
    at IntroProjectilePanel.setRight (https://bayes.colorado.edu/continuous-testing/snapshot-1536838001842/scenery/js/nodes/Node.js?bust=1536838748290:2511:17)
    at IntroProjectilePanel.set right [as right] (https://bayes.colorado.edu/continuous-testing/snapshot-1536838001842/scenery/js/nodes/Node.js?bust=1536838748290:2517:31)
    at IntroScreenView.layout (https://bayes.colorado.edu/continuous-testing/snapshot-1536838001842/projectile-motion/js/common/view/ProjectileMotionScreenView.js?bust=1536838748290:447:32)
    at IntroScreenView.layout (https://bayes.colorado.edu/continuous-testing/snapshot-1536838001842/projectile-motion/js/intro/view/IntroScreenView.js?bust=1536838748290:68:51)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1536838001842/joist/js/Sim.js?bust=1536838748290:631:16
    at u (https://bayes.colorado.edu/continuous-testing/snapshot-1536838001842/sherpa/lib/lodash-4.17.4.min.js?bust=1536838748290:5:432)
    at Function.ru (https://bayes.colorado.edu/continuous-testing/snapshot-1536838001842/sherpa/lib/lodash-4.17.4.min.js?bust=1536838748290:67:656)
    at Sim.resize (https://bayes.colorado.edu/continuous-testing/snapshot-1536838001842/joist/js/Sim.js?bust=1536838748290:630:9)
    at Sim.resizeToWindow (https://bayes.colorado.edu/continuous-testing/snapshot-1536838001842/joist/js/Sim.js?bust=1536838748290:608:12)
Approximately 9/13/2018, 5:26:41 AM
projectile-motion : xss-fuzz : load
Uncaught Error: Assertion failed: Setting right is invalid when the node has invalid (empty/NaN/infinite) bounds.
Error: Assertion failed: Setting right is invalid when the node has invalid (empty/NaN/infinite) bounds.
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1536838001842/assert/js/assert.js:22:13)
    at IntroProjectilePanel.setRight (https://bayes.colorado.edu/continuous-testing/snapshot-1536838001842/scenery/js/nodes/Node.js?bust=1536841506592:2511:17)
    at IntroProjectilePanel.set right [as right] (https://bayes.colorado.edu/continuous-testing/snapshot-1536838001842/scenery/js/nodes/Node.js?bust=1536841506592:2517:31)
    at IntroScreenView.layout (https://bayes.colorado.edu/continuous-testing/snapshot-1536838001842/projectile-motion/js/common/view/ProjectileMotionScreenView.js?bust=1536841506592:447:32)
    at IntroScreenView.layout (https://bayes.colorado.edu/continuous-testing/snapshot-1536838001842/projectile-motion/js/intro/view/IntroScreenView.js?bust=1536841506592:68:51)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1536838001842/joist/js/Sim.js?bust=1536841506592:631:16
    at u (https://bayes.colorado.edu/continuous-testing/snapshot-1536838001842/sherpa/lib/lodash-4.17.4.min.js?bust=1536841506592:5:432)
    at Function.ru (https://bayes.colorado.edu/continuous-testing/snapshot-1536838001842/sherpa/lib/lodash-4.17.4.min.js?bust=1536841506592:67:656)
    at Sim.resize (https://bayes.colorado.edu/continuous-testing/snapshot-1536838001842/joist/js/Sim.js?bust=1536841506592:630:9)
    at Sim.resizeToWindow (https://bayes.colorado.edu/continuous-testing/snapshot-1536838001842/joist/js/Sim.js?bust=1536841506592:608:12)
Approximately 9/13/2018, 5:26:41 AM
projectile-motion : xss-fuzz : load
Uncaught Error: Assertion failed: Setting right is invalid when the node has invalid (empty/NaN/infinite) bounds.
Error: Assertion failed: Setting right is invalid when the node has invalid (empty/NaN/infinite) bounds.
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1536838001842/assert/js/assert.js:22:13)
    at IntroProjectilePanel.setRight (https://bayes.colorado.edu/continuous-testing/snapshot-1536838001842/scenery/js/nodes/Node.js?bust=1536845637009:2511:17)
    at IntroProjectilePanel.set right [as right] (https://bayes.colorado.edu/continuous-testing/snapshot-1536838001842/scenery/js/nodes/Node.js?bust=1536845637009:2517:31)
    at IntroScreenView.layout (https://bayes.colorado.edu/continuous-testing/snapshot-1536838001842/projectile-motion/js/common/view/ProjectileMotionScreenView.js?bust=1536845637009:447:32)
    at IntroScreenView.layout (https://bayes.colorado.edu/continuous-testing/snapshot-1536838001842/projectile-motion/js/intro/view/IntroScreenView.js?bust=1536845637009:68:51)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1536838001842/joist/js/Sim.js?bust=1536845637009:631:16
    at u (https://bayes.colorado.edu/continuous-testing/snapshot-1536838001842/sherpa/lib/lodash-4.17.4.min.js?bust=1536845637009:5:432)
    at Function.ru (https://bayes.colorado.edu/continuous-testing/snapshot-1536838001842/sherpa/lib/lodash-4.17.4.min.js?bust=1536845637009:67:656)
    at Sim.resize (https://bayes.colorado.edu/continuous-testing/snapshot-1536838001842/joist/js/Sim.js?bust=1536845637009:630:9)
    at Sim.resizeToWindow (https://bayes.colorado.edu/continuous-testing/snapshot-1536838001842/joist/js/Sim.js?bust=1536845637009:608:12)
Approximately 9/13/2018, 5:26:41 AM
projectile-motion : xss-fuzz : load
Uncaught Error: Assertion failed: Setting right is invalid when the node has invalid (empty/NaN/infinite) bounds.
Error: Assertion failed: Setting right is invalid when the node has invalid (empty/NaN/infinite) bounds.
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1536838001842/assert/js/assert.js:22:13)
    at IntroProjectilePanel.setRight (https://bayes.colorado.edu/continuous-testing/snapshot-1536838001842/scenery/js/nodes/Node.js?bust=1536846154502:2511:17)
    at IntroProjectilePanel.set right [as right] (https://bayes.colorado.edu/continuous-testing/snapshot-1536838001842/scenery/js/nodes/Node.js?bust=1536846154502:2517:31)
    at IntroScreenView.layout (https://bayes.colorado.edu/continuous-testing/snapshot-1536838001842/projectile-motion/js/common/view/ProjectileMotionScreenView.js?bust=1536846154502:447:32)
    at IntroScreenView.layout (https://bayes.colorado.edu/continuous-testing/snapshot-1536838001842/projectile-motion/js/intro/view/IntroScreenView.js?bust=1536846154502:68:51)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1536838001842/joist/js/Sim.js?bust=1536846154502:631:16
    at u (https://bayes.colorado.edu/continuous-testing/snapshot-1536838001842/sherpa/lib/lodash-4.17.4.min.js?bust=1536846154502:5:432)
    at Function.ru (https://bayes.colorado.edu/continuous-testing/snapshot-1536838001842/sherpa/lib/lodash-4.17.4.min.js?bust=1536846154502:67:656)
    at Sim.resize (https://bayes.colorado.edu/continuous-testing/snapshot-1536838001842/joist/js/Sim.js?bust=1536846154502:630:9)
    at Sim.resizeToWindow (https://bayes.colorado.edu/continuous-testing/snapshot-1536838001842/joist/js/Sim.js?bust=1536846154502:608:12)
Approximately 9/13/2018, 5:26:41 AM
projectile-motion : xss-fuzz : load
Uncaught Error: Assertion failed: Setting right is invalid when the node has invalid (empty/NaN/infinite) bounds.
Error: Assertion failed: Setting right is invalid when the node has invalid (empty/NaN/infinite) bounds.
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1536838001842/assert/js/assert.js:22:13)
    at IntroProjectilePanel.setRight (https://bayes.colorado.edu/continuous-testing/snapshot-1536838001842/scenery/js/nodes/Node.js?bust=1536849277662:2511:17)
    at IntroProjectilePanel.set right [as right] (https://bayes.colorado.edu/continuous-testing/snapshot-1536838001842/scenery/js/nodes/Node.js?bust=1536849277662:2517:31)
    at IntroScreenView.layout (https://bayes.colorado.edu/continuous-testing/snapshot-1536838001842/projectile-motion/js/common/view/ProjectileMotionScreenView.js?bust=1536849277662:447:32)
    at IntroScreenView.layout (https://bayes.colorado.edu/continuous-testing/snapshot-1536838001842/projectile-motion/js/intro/view/IntroScreenView.js?bust=1536849277662:68:51)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1536838001842/joist/js/Sim.js?bust=1536849277662:631:16
    at u (https://bayes.colorado.edu/continuous-testing/snapshot-1536838001842/sherpa/lib/lodash-4.17.4.min.js?bust=1536849277662:5:432)
    at Function.ru (https://bayes.colorado.edu/continuous-testing/snapshot-1536838001842/sherpa/lib/lodash-4.17.4.min.js?bust=1536849277662:67:656)
    at Sim.resize (https://bayes.colorado.edu/continuous-testing/snapshot-1536838001842/joist/js/Sim.js?bust=1536849277662:630:9)
    at Sim.resizeToWindow (https://bayes.colorado.edu/continuous-testing/snapshot-1536838001842/joist/js/Sim.js?bust=1536849277662:608:12)
Approximately 9/13/2018, 5:26:41 AM
projectile-motion : xss-fuzz : run
Uncaught Error: Assertion failed: Setting right is invalid when the node has invalid (empty/NaN/infinite) bounds.
Error: Assertion failed: Setting right is invalid when the node has invalid (empty/NaN/infinite) bounds.
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1536838001842/assert/js/assert.js:22:13)
    at IntroProjectilePanel.setRight (https://bayes.colorado.edu/continuous-testing/snapshot-1536838001842/scenery/js/nodes/Node.js?bust=1536838748290:2511:17)
    at IntroProjectilePanel.set right [as right] (https://bayes.colorado.edu/continuous-testing/snapshot-1536838001842/scenery/js/nodes/Node.js?bust=1536838748290:2517:31)
    at IntroScreenView.layout (https://bayes.colorado.edu/continuous-testing/snapshot-1536838001842/projectile-motion/js/common/view/ProjectileMotionScreenView.js?bust=1536838748290:447:32)
    at IntroScreenView.layout (https://bayes.colorado.edu/continuous-testing/snapshot-1536838001842/projectile-motion/js/intro/view/IntroScreenView.js?bust=1536838748290:68:51)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1536838001842/joist/js/Sim.js?bust=1536838748290:631:16
    at u (https://bayes.colorado.edu/continuous-testing/snapshot-1536838001842/sherpa/lib/lodash-4.17.4.min.js?bust=1536838748290:5:432)
    at Function.ru (https://bayes.colorado.edu/continuous-testing/snapshot-1536838001842/sherpa/lib/lodash-4.17.4.min.js?bust=1536838748290:67:656)
    at Sim.resize (https://bayes.colorado.edu/continuous-testing/snapshot-1536838001842/joist/js/Sim.js?bust=1536838748290:630:9)
    at Sim.resizeToWindow (https://bayes.colorado.edu/continuous-testing/snapshot-1536838001842/joist/js/Sim.js?bust=1536838748290:608:12)
Approximately 9/13/2018, 5:26:41 AM
projectile-motion : xss-fuzz : run
Uncaught Error: Assertion failed: Setting right is invalid when the node has invalid (empty/NaN/infinite) bounds.
Error: Assertion failed: Setting right is invalid when the node has invalid (empty/NaN/infinite) bounds.
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1536838001842/assert/js/assert.js:22:13)
    at IntroProjectilePanel.setRight (https://bayes.colorado.edu/continuous-testing/snapshot-1536838001842/scenery/js/nodes/Node.js?bust=1536841506592:2511:17)
    at IntroProjectilePanel.set right [as right] (https://bayes.colorado.edu/continuous-testing/snapshot-1536838001842/scenery/js/nodes/Node.js?bust=1536841506592:2517:31)
    at IntroScreenView.layout (https://bayes.colorado.edu/continuous-testing/snapshot-1536838001842/projectile-motion/js/common/view/ProjectileMotionScreenView.js?bust=1536841506592:447:32)
    at IntroScreenView.layout (https://bayes.colorado.edu/continuous-testing/snapshot-1536838001842/projectile-motion/js/intro/view/IntroScreenView.js?bust=1536841506592:68:51)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1536838001842/joist/js/Sim.js?bust=1536841506592:631:16
    at u (https://bayes.colorado.edu/continuous-testing/snapshot-1536838001842/sherpa/lib/lodash-4.17.4.min.js?bust=1536841506592:5:432)
    at Function.ru (https://bayes.colorado.edu/continuous-testing/snapshot-1536838001842/sherpa/lib/lodash-4.17.4.min.js?bust=1536841506592:67:656)
    at Sim.resize (https://bayes.colorado.edu/continuous-testing/snapshot-1536838001842/joist/js/Sim.js?bust=1536841506592:630:9)
    at Sim.resizeToWindow (https://bayes.colorado.edu/continuous-testing/snapshot-1536838001842/joist/js/Sim.js?bust=1536841506592:608:12)
Approximately 9/13/2018, 5:26:41 AM
projectile-motion : xss-fuzz : run
Uncaught Error: Assertion failed: Setting right is invalid when the node has invalid (empty/NaN/infinite) bounds.
Error: Assertion failed: Setting right is invalid when the node has invalid (empty/NaN/infinite) bounds.
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1536838001842/assert/js/assert.js:22:13)
    at IntroProjectilePanel.setRight (https://bayes.colorado.edu/continuous-testing/snapshot-1536838001842/scenery/js/nodes/Node.js?bust=1536845637009:2511:17)
    at IntroProjectilePanel.set right [as right] (https://bayes.colorado.edu/continuous-testing/snapshot-1536838001842/scenery/js/nodes/Node.js?bust=1536845637009:2517:31)
    at IntroScreenView.layout (https://bayes.colorado.edu/continuous-testing/snapshot-1536838001842/projectile-motion/js/common/view/ProjectileMotionScreenView.js?bust=1536845637009:447:32)
    at IntroScreenView.layout (https://bayes.colorado.edu/continuous-testing/snapshot-1536838001842/projectile-motion/js/intro/view/IntroScreenView.js?bust=1536845637009:68:51)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1536838001842/joist/js/Sim.js?bust=1536845637009:631:16
    at u (https://bayes.colorado.edu/continuous-testing/snapshot-1536838001842/sherpa/lib/lodash-4.17.4.min.js?bust=1536845637009:5:432)
    at Function.ru (https://bayes.colorado.edu/continuous-testing/snapshot-1536838001842/sherpa/lib/lodash-4.17.4.min.js?bust=1536845637009:67:656)
    at Sim.resize (https://bayes.colorado.edu/continuous-testing/snapshot-1536838001842/joist/js/Sim.js?bust=1536845637009:630:9)
    at Sim.resizeToWindow (https://bayes.colorado.edu/continuous-testing/snapshot-1536838001842/joist/js/Sim.js?bust=1536845637009:608:12)
Approximately 9/13/2018, 5:26:41 AM
projectile-motion : xss-fuzz : run
Uncaught Error: Assertion failed: Setting right is invalid when the node has invalid (empty/NaN/infinite) bounds.
Error: Assertion failed: Setting right is invalid when the node has invalid (empty/NaN/infinite) bounds.
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1536838001842/assert/js/assert.js:22:13)
    at IntroProjectilePanel.setRight (https://bayes.colorado.edu/continuous-testing/snapshot-1536838001842/scenery/js/nodes/Node.js?bust=1536846154502:2511:17)
    at IntroProjectilePanel.set right [as right] (https://bayes.colorado.edu/continuous-testing/snapshot-1536838001842/scenery/js/nodes/Node.js?bust=1536846154502:2517:31)
    at IntroScreenView.layout (https://bayes.colorado.edu/continuous-testing/snapshot-1536838001842/projectile-motion/js/common/view/ProjectileMotionScreenView.js?bust=1536846154502:447:32)
    at IntroScreenView.layout (https://bayes.colorado.edu/continuous-testing/snapshot-1536838001842/projectile-motion/js/intro/view/IntroScreenView.js?bust=1536846154502:68:51)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1536838001842/joist/js/Sim.js?bust=1536846154502:631:16
    at u (https://bayes.colorado.edu/continuous-testing/snapshot-1536838001842/sherpa/lib/lodash-4.17.4.min.js?bust=1536846154502:5:432)
    at Function.ru (https://bayes.colorado.edu/continuous-testing/snapshot-1536838001842/sherpa/lib/lodash-4.17.4.min.js?bust=1536846154502:67:656)
    at Sim.resize (https://bayes.colorado.edu/continuous-testing/snapshot-1536838001842/joist/js/Sim.js?bust=1536846154502:630:9)
    at Sim.resizeToWindow (https://bayes.colorado.edu/continuous-testing/snapshot-1536838001842/joist/js/Sim.js?bust=1536846154502:608:12)
Approximately 9/13/2018, 5:26:41 AM
projectile-motion : xss-fuzz : run
Uncaught Error: Assertion failed: Setting right is invalid when the node has invalid (empty/NaN/infinite) bounds.
Error: Assertion failed: Setting right is invalid when the node has invalid (empty/NaN/infinite) bounds.
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1536838001842/assert/js/assert.js:22:13)
    at IntroProjectilePanel.setRight (https://bayes.colorado.edu/continuous-testing/snapshot-1536838001842/scenery/js/nodes/Node.js?bust=1536849277662:2511:17)
    at IntroProjectilePanel.set right [as right] (https://bayes.colorado.edu/continuous-testing/snapshot-1536838001842/scenery/js/nodes/Node.js?bust=1536849277662:2517:31)
    at IntroScreenView.layout (https://bayes.colorado.edu/continuous-testing/snapshot-1536838001842/projectile-motion/js/common/view/ProjectileMotionScreenView.js?bust=1536849277662:447:32)
    at IntroScreenView.layout (https://bayes.colorado.edu/continuous-testing/snapshot-1536838001842/projectile-motion/js/intro/view/IntroScreenView.js?bust=1536849277662:68:51)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1536838001842/joist/js/Sim.js?bust=1536849277662:631:16
    at u (https://bayes.colorado.edu/continuous-testing/snapshot-1536838001842/sherpa/lib/lodash-4.17.4.min.js?bust=1536849277662:5:432)
    at Function.ru (https://bayes.colorado.edu/continuous-testing/snapshot-1536838001842/sherpa/lib/lodash-4.17.4.min.js?bust=1536849277662:67:656)
    at Sim.resize (https://bayes.colorado.edu/continuous-testing/snapshot-1536838001842/joist/js/Sim.js?bust=1536849277662:630:9)
    at Sim.resizeToWindow (https://bayes.colorado.edu/continuous-testing/snapshot-1536838001842/joist/js/Sim.js?bust=1536849277662:608:12)
Approximately 9/13/2018, 5:26:41 AM
```

**Comment by samreid** [comment]
Reassigning to @jbphet since he is listed as responsible dev for this sim.

**Comment by jbphet** [comment]
I'm able to duplicate this on my machine with the following URL:
```
http://localhost:8080/projectile-motion/projectile-motion_en.html?brand=phet&ea&screens=1&stringTest=xss
```

So why is the xss test suddenly failing for this sim?

I just tried running with ```stringTest=xss``` on the published version (v1.0.5), and the test doesn't cause the sim to crash, but the first screen is all white, so perhaps this was an issue before but it just didn't hit an assertion.

**Comment by jbphet** [comment]
I took a few minutes to look at this.  What I can see is that during the `stringTest=xss` test, when `IntroProjectilePanel` is constructed in `IntroScreenView`, the panel has `NaN` values for all bounds properties.  Further digging showed that the "boxes" that were being created by the `createParameterControlBox` function was returning nodes with invalid bounds.  I tried commenting out the line that set the bounds method to be 'accurate' (see commit linked above) and this made the problem go away.  I couldn't notice any significant difference in the way the panel looked with this line commented out, but since the original author probably did it for a reason, and since it doesn't seem like setting bounds method to 'accurate' should cause this sort of a problem, I think we should investigate further.

Since this seems like a scenery issue, I'm assigning to @jonathanolson and leaving myself assigned for final followup.

**Comment by jonathanolson** [comment]
Looks like asymmetric initial scaling may work for accurate bounds:

![asymmetric-scaling](https://user-images.githubusercontent.com/480878/45651335-6eb0c100-ba8e-11e8-9bd6-292295170b64.png)

whereas if we apply the ~0.005 scaling factor in both dimensions (instead of the ~0.005 in one and ~3 in the other shown here), it disappears completely when displayed.

**Comment by jonathanolson** [comment]
Pushed a fix so that things fall back to the "SVG" bounds when the "accurate" ones cannot be computed. I looked into properly handling this, but splitting the initial coarse checks into one for each dimension ran into its own issues.

@jbphet you should be able to remove the workaround in the sim now.

**Comment by jbphet** [comment]
Yep, it works now with the accurate bounds setting.  Thanks @jonathanolson! Closing.
