### ISSUE TITLE
CT mapped to value that is wider than the NumberDisplay background

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/projectile-motion#167]
```
projectile-motion : fuzz : require.js : run
Uncaught Error: Assertion failed: mapped to value that is wider than the NumberDisplay background
Error: Assertion failed: mapped to value that is wider than the NumberDisplay background
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1544980472044/assert/js/assert.js:22:13)
    at Array.numberObserver (https://bayes.colorado.edu/continuous-testing/snapshot-1544980472044/scenery-phet/js/NumberDisplay.js?bust=1544986758282:107:17)
    at Emitter.emit3 (https://bayes.colorado.edu/continuous-testing/snapshot-1544980472044/axon/js/Emitter.js?bust=1544986758282:281:54)
    at NumberProperty._notifyListeners (https://bayes.colorado.edu/continuous-testing/snapshot-1544980472044/axon/js/Property.js?bust=1544986758282:288:29)
    at NumberProperty.setValueAndNotifyListeners (https://bayes.colorado.edu/continuous-testing/snapshot-1544980472044/axon/js/Property.js?bust=1544986758282:270:14)
    at NumberProperty.set (https://bayes.colorado.edu/continuous-testing/snapshot-1544980472044/axon/js/Property.js?bust=1544986758282:203:16)
    at NumberProperty.set (https://bayes.colorado.edu/continuous-testing/snapshot-1544980472044/axon/js/NumberProperty.js?bust=1544986758282:84:30)
    at LabModel.setProjectileParameters (https://bayes.colorado.edu/continuous-testing/snapshot-1544980472044/projectile-motion/js/lab/model/LabModel.js?bust=1544986758282:108:37)
    at Emitter.emit3 (https://bayes.colorado.edu/continuous-testing/snapshot-1544980472044/axon/js/Emitter.js?bust=1544986758282:281:54)
    at Property._notifyListeners (https://bayes.colorado.edu/continuous-testing/snapshot-1544980472044/axon/js/Property.js?bust=1544986758282:288:29)
id: Bayes Chrome
Approximately 12/16/2018, 10:14:32 AM
projectile-motion : fuzz : require.js : run
Uncaught Error: Assertion failed: reentry detected, value=2.38, oldValue=17.6
Error: Assertion failed: reentry detected, value=2.38, oldValue=17.6
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1544980472044/assert/js/assert.js:22:13)
    at NumberProperty._notifyListeners (https://bayes.colorado.edu/continuous-testing/snapshot-1544980472044/axon/js/Property.js?bust=1544986758282:285:19)
    at NumberProperty.setValueAndNotifyListeners (https://bayes.colorado.edu/continuous-testing/snapshot-1544980472044/axon/js/Property.js?bust=1544986758282:270:14)
    at NumberProperty.set (https://bayes.colorado.edu/continuous-testing/snapshot-1544980472044/axon/js/Property.js?bust=1544986758282:203:16)
    at NumberProperty.set (https://bayes.colorado.edu/continuous-testing/snapshot-1544980472044/axon/js/NumberProperty.js?bust=1544986758282:84:30)
    at drag (https://bayes.colorado.edu/continuous-testing/snapshot-1544980472044/sun/js/Slider.js?bust=1544986758282:239:25)
    at Emitter.listener (https://bayes.colorado.edu/continuous-testing/snapshot-1544980472044/scenery/js/input/SimpleDragHandler.js?bust=1544986758282:140:29)
    at Emitter.emit (https://bayes.colorado.edu/continuous-testing/snapshot-1544980472044/axon/js/Emitter.js?bust=1544986758282:202:55)
    at Object.move (https://bayes.colorado.edu/continuous-testing/snapshot-1544980472044/scenery/js/input/SimpleDragHandler.js?bust=1544986758282:239:29)
    at Input.dispatchToListeners (https://bayes.colorado.edu/continuous-testing/snapshot-1544980472044/scenery/js/input/Input.js?bust=1544986758282:1664:27)
id: Bayes Chrome
Approximately 12/16/2018, 10:14:32 AM
projectile-motion : fuzz : require.js : run
Uncaught Error: Assertion failed: mapped to value that is wider than the NumberDisplay background
Error: Assertion failed: mapped to value that is wider than the NumberDisplay background
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1544980472044/assert/js/assert.js:22:13)
    at Array.numberObserver (https://bayes.colorado.edu/continuous-testing/snapshot-1544980472044/scenery-phet/js/NumberDisplay.js?bust=1544998922841:107:17)
    at Emitter.emit3 (https://bayes.colorado.edu/continuous-testing/snapshot-1544980472044/axon/js/Emitter.js?bust=1544998922841:281:54)
    at NumberProperty._notifyListeners (https://bayes.colorado.edu/continuous-testing/snapshot-1544980472044/axon/js/Property.js?bust=1544998922841:288:29)
    at NumberProperty.setValueAndNotifyListeners (https://bayes.colorado.edu/continuous-testing/snapshot-1544980472044/axon/js/Property.js?bust=1544998922841:270:14)
    at NumberProperty.set (https://bayes.colorado.edu/continuous-testing/snapshot-1544980472044/axon/js/Property.js?bust=1544998922841:203:16)
    at NumberProperty.set (https://bayes.colorado.edu/continuous-testing/snapshot-1544980472044/axon/js/NumberProperty.js?bust=1544998922841:84:30)
    at LabModel.setProjectileParameters (https://bayes.colorado.edu/continuous-testing/snapshot-1544980472044/projectile-motion/js/lab/model/LabModel.js?bust=1544998922841:113:37)
    at Emitter.emit3 (https://bayes.colorado.edu/continuous-testing/snapshot-1544980472044/axon/js/Emitter.js?bust=1544998922841:281:54)
    at Property._notifyListeners (https://bayes.colorado.edu/continuous-testing/snapshot-1544980472044/axon/js/Property.js?bust=1544998922841:288:29)
id: Bayes Chrome
Approximately 12/16/2018, 10:14:32 AM
projectile-motion : fuzz : require.js : run
Uncaught Error: Assertion failed: mapped to value that is wider than the NumberDisplay background
Error: Assertion failed: mapped to value that is wider than the NumberDisplay background
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1544980472044/assert/js/assert.js:22:13)
    at Array.numberObserver (https://bayes.colorado.edu/continuous-testing/snapshot-1544980472044/scenery-phet/js/NumberDisplay.js?bust=1545021088341:107:17)
    at Emitter.emit3 (https://bayes.colorado.edu/continuous-testing/snapshot-1544980472044/axon/js/Emitter.js?bust=1545021088341:281:54)
    at NumberProperty._notifyListeners (https://bayes.colorado.edu/continuous-testing/snapshot-1544980472044/axon/js/Property.js?bust=1545021088341:288:29)
    at NumberProperty.setValueAndNotifyListeners (https://bayes.colorado.edu/continuous-testing/snapshot-1544980472044/axon/js/Property.js?bust=1545021088341:270:14)
    at NumberProperty.set (https://bayes.colorado.edu/continuous-testing/snapshot-1544980472044/axon/js/Property.js?bust=1545021088341:203:16)
    at NumberProperty.set (https://bayes.colorado.edu/continuous-testing/snapshot-1544980472044/axon/js/NumberProperty.js?bust=1545021088341:84:30)
    at LabModel.setProjectileParameters (https://bayes.colorado.edu/continuous-testing/snapshot-1544980472044/projectile-motion/js/lab/model/LabModel.js?bust=1545021088341:113:37)
    at Emitter.emit3 (https://bayes.colorado.edu/continuous-testing/snapshot-1544980472044/axon/js/Emitter.js?bust=1545021088341:281:54)
    at Property._notifyListeners (https://bayes.colorado.edu/continuous-testing/snapshot-1544980472044/axon/js/Property.js?bust=1545021088341:288:29)
id: Bayes Chrome
Approximately 12/16/2018, 10:14:32 AM
projectile-motion : fuzz : require.js : run
Uncaught Error: Assertion failed: mapped to value that is wider than the NumberDisplay background
Error: Assertion failed: mapped to value that is wider than the NumberDisplay background
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1544980472044/assert/js/assert.js:22:13)
    at Array.numberObserver (https://bayes.colorado.edu/continuous-testing/snapshot-1544980472044/scenery-phet/js/NumberDisplay.js?bust=1545031563391:107:17)
    at Emitter.emit3 (https://bayes.colorado.edu/continuous-testing/snapshot-1544980472044/axon/js/Emitter.js?bust=1545031563391:281:54)
    at NumberProperty._notifyListeners (https://bayes.colorado.edu/continuous-testing/snapshot-1544980472044/axon/js/Property.js?bust=1545031563391:288:29)
    at NumberProperty.setValueAndNotifyListeners (https://bayes.colorado.edu/continuous-testing/snapshot-1544980472044/axon/js/Property.js?bust=1545031563391:270:14)
    at NumberProperty.set (https://bayes.colorado.edu/continuous-testing/snapshot-1544980472044/axon/js/Property.js?bust=1545031563391:203:16)
    at NumberProperty.set (https://bayes.colorado.edu/continuous-testing/snapshot-1544980472044/axon/js/NumberProperty.js?bust=1545031563391:84:30)
    at LabModel.setProjectileParameters (https://bayes.colorado.edu/continuous-testing/snapshot-1544980472044/projectile-motion/js/lab/model/LabModel.js?bust=1545031563391:108:37)
    at Emitter.emit3 (https://bayes.colorado.edu/continuous-testing/snapshot-1544980472044/axon/js/Emitter.js?bust=1545031563391:281:54)
    at Property._notifyListeners (https://bayes.colorado.edu/continuous-testing/snapshot-1544980472044/axon/js/Property.js?bust=1545031563391:288:29)
id: Bayes Chrome
Approximately 12/16/2018, 10:14:32 AM
projectile-motion : fuzz : require.js : run
Uncaught Error: Assertion failed: mapped to value that is wider than the NumberDisplay background
Error: Assertion failed: mapped to value that is wider than the NumberDisplay background
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1544980472044/assert/js/assert.js:22:13)
    at Array.numberObserver (https://bayes.colorado.edu/continuous-testing/snapshot-1544980472044/scenery-phet/js/NumberDisplay.js?bust=1545048738397:107:17)
    at Emitter.emit3 (https://bayes.colorado.edu/continuous-testing/snapshot-1544980472044/axon/js/Emitter.js?bust=1545048738397:281:54)
    at NumberProperty._notifyListeners (https://bayes.colorado.edu/continuous-testing/snapshot-1544980472044/axon/js/Property.js?bust=1545048738397:288:29)
    at NumberProperty.setValueAndNotifyListeners (https://bayes.colorado.edu/continuous-testing/snapshot-1544980472044/axon/js/Property.js?bust=1545048738397:270:14)
    at NumberProperty.set (https://bayes.colorado.edu/continuous-testing/snapshot-1544980472044/axon/js/Property.js?bust=1545048738397:203:16)
    at NumberProperty.set (https://bayes.colorado.edu/continuous-testing/snapshot-1544980472044/axon/js/NumberProperty.js?bust=1545048738397:84:30)
    at LabModel.setProjectileParameters (https://bayes.colorado.edu/continuous-testing/snapshot-1544980472044/projectile-motion/js/lab/model/LabModel.js?bust=1545048738397:108:37)
    at Emitter.emit3 (https://bayes.colorado.edu/continuous-testing/snapshot-1544980472044/axon/js/Emitter.js?bust=1545048738397:281:54)
    at Property._notifyListeners (https://bayes.colorado.edu/continuous-testing/snapshot-1544980472044/axon/js/Property.js?bust=1545048738397:288:29)
id: Bayes Chrome
Approximately 12/16/2018, 10:14:32 AM
projectile-motion : fuzz : require.js : run
Uncaught Error: Assertion failed: mapped to value that is wider than the NumberDisplay background
Error: Assertion failed: mapped to value that is wider than the NumberDisplay background
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1544980472044/assert/js/assert.js:22:13)
    at Array.numberObserver (https://bayes.colorado.edu/continuous-testing/snapshot-1544980472044/scenery-phet/js/NumberDisplay.js?bust=1545060482537:107:17)
    at Emitter.emit3 (https://bayes.colorado.edu/continuous-testing/snapshot-1544980472044/axon/js/Emitter.js?bust=1545060482537:281:54)
    at NumberProperty._notifyListeners (https://bayes.colorado.edu/continuous-testing/snapshot-1544980472044/axon/js/Property.js?bust=1545060482537:288:29)
    at NumberProperty.setValueAndNotifyListeners (https://bayes.colorado.edu/continuous-testing/snapshot-1544980472044/axon/js/Property.js?bust=1545060482537:270:14)
    at NumberProperty.set (https://bayes.colorado.edu/continuous-testing/snapshot-1544980472044/axon/js/Property.js?bust=1545060482537:203:16)
    at NumberProperty.set (https://bayes.colorado.edu/continuous-testing/snapshot-1544980472044/axon/js/NumberProperty.js?bust=1545060482537:84:30)
    at LabModel.setProjectileParameters (https://bayes.colorado.edu/continuous-testing/snapshot-1544980472044/projectile-motion/js/lab/model/LabModel.js?bust=1545060482537:113:37)
    at Emitter.emit3 (https://bayes.colorado.edu/continuous-testing/snapshot-1544980472044/axon/js/Emitter.js?bust=1545060482537:281:54)
    at Property._notifyListeners (https://bayes.colorado.edu/continuous-testing/snapshot-1544980472044/axon/js/Property.js?bust=1545060482537:288:29)
id: Bayes Chrome
Approximately 12/16/2018, 10:14:32 AM
projectile-motion : fuzz : require.js-canvas : run
Uncaught Error: Assertion failed: mapped to value that is wider than the NumberDisplay background
Error: Assertion failed: mapped to value that is wider than the NumberDisplay background
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1544980472044/assert/js/assert.js:22:13)
    at Array.numberObserver (https://bayes.colorado.edu/continuous-testing/snapshot-1544980472044/scenery-phet/js/NumberDisplay.js?bust=1544991896858:107:17)
    at Emitter.emit3 (https://bayes.colorado.edu/continuous-testing/snapshot-1544980472044/axon/js/Emitter.js?bust=1544991896858:281:54)
    at NumberProperty._notifyListeners (https://bayes.colorado.edu/continuous-testing/snapshot-1544980472044/axon/js/Property.js?bust=1544991896858:288:29)
    at NumberProperty.setValueAndNotifyListeners (https://bayes.colorado.edu/continuous-testing/snapshot-1544980472044/axon/js/Property.js?bust=1544991896858:270:14)
    at NumberProperty.set (https://bayes.colorado.edu/continuous-testing/snapshot-1544980472044/axon/js/Property.js?bust=1544991896858:203:16)
    at NumberProperty.set (https://bayes.colorado.edu/continuous-testing/snapshot-1544980472044/axon/js/NumberProperty.js?bust=1544991896858:84:30)
    at LabModel.setProjectileParameters (https://bayes.colorado.edu/continuous-testing/snapshot-1544980472044/projectile-motion/js/lab/model/LabModel.js?bust=1544991896858:108:37)
    at Emitter.emit3 (https://bayes.colorado.edu/continuous-testing/snapshot-1544980472044/axon/js/Emitter.js?bust=1544991896858:281:54)
    at Property._notifyListeners (https://bayes.colorado.edu/continuous-testing/snapshot-1544980472044/axon/js/Property.js?bust=1544991896858:288:29)
id: Bayes Chrome
Approximately 12/16/2018, 10:14:32 AM
projectile-motion : fuzz : require.js-canvas : run
Uncaught Error: Assertion failed: mapped to value that is wider than the NumberDisplay background
Error: Assertion failed: mapped to value that is wider than the NumberDisplay background
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1544980472044/assert/js/assert.js:22:13)
    at Array.numberObserver (https://bayes.colorado.edu/continuous-testing/snapshot-1544980472044/scenery-phet/js/NumberDisplay.js?bust=1545003403409:107:17)
    at Emitter.emit3 (https://bayes.colorado.edu/continuous-testing/snapshot-1544980472044/axon/js/Emitter.js?bust=1545003403409:281:54)
    at NumberProperty._notifyListeners (https://bayes.colorado.edu/continuous-testing/snapshot-1544980472044/axon/js/Property.js?bust=1545003403409:288:29)
    at NumberProperty.setValueAndNotifyListeners (https://bayes.colorado.edu/continuous-testing/snapshot-1544980472044/axon/js/Property.js?bust=1545003403409:270:14)
    at NumberProperty.set (https://bayes.colorado.edu/continuous-testing/snapshot-1544980472044/axon/js/Property.js?bust=1545003403409:203:16)
    at NumberProperty.set (https://bayes.colorado.edu/continuous-testing/snapshot-1544980472044/axon/js/NumberProperty.js?bust=1545003403409:84:30)
    at LabModel.setProjectileParameters (https://bayes.colorado.edu/continuous-testing/snapshot-1544980472044/projectile-motion/js/lab/model/LabModel.js?bust=1545003403409:113:37)
    at Emitter.emit3 (https://bayes.colorado.edu/continuous-testing/snapshot-1544980472044/axon/js/Emitter.js?bust=1545003403409:281:54)
    at Property._notifyListeners (https://bayes.colorado.edu/continuous-testing/snapshot-1544980472044/axon/js/Property.js?bust=1545003403409:288:29)
id: Bayes Chrome
Approximately 12/16/2018, 10:14:32 AM
projectile-motion : fuzz : require.js-canvas : run
Uncaught Error: Assertion failed: mapped to value that is wider than the NumberDisplay background
Error: Assertion failed: mapped to value that is wider than the NumberDisplay background
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1544980472044/assert/js/assert.js:22:13)
    at Array.numberObserver (https://bayes.colorado.edu/continuous-testing/snapshot-1544980472044/scenery-phet/js/NumberDisplay.js?bust=1545012687057:107:17)
    at Emitter.emit3 (https://bayes.colorado.edu/continuous-testing/snapshot-1544980472044/axon/js/Emitter.js?bust=1545012687057:281:54)
    at NumberProperty._notifyListeners (https://bayes.colorado.edu/continuous-testing/snapshot-1544980472044/axon/js/Property.js?bust=1545012687057:288:29)
    at NumberProperty.setValueAndNotifyListeners (https://bayes.colorado.edu/continuous-testing/snapshot-1544980472044/axon/js/Property.js?bust=1545012687057:270:14)
    at NumberProperty.set (https://bayes.colorado.edu/continuous-testing/snapshot-1544980472044/axon/js/Property.js?bust=1545012687057:203:16)
    at NumberProperty.set (https://bayes.colorado.edu/continuous-testing/snapshot-1544980472044/axon/js/NumberProperty.js?bust=1545012687057:84:30)
    at LabModel.setProjectileParameters (https://bayes.colorado.edu/continuous-testing/snapshot-1544980472044/projectile-motion/js/lab/model/LabModel.js?bust=1545012687057:108:37)
    at Emitter.emit3 (https://bayes.colorado.edu/continuous-testing/snapshot-1544980472044/axon/js/Emitter.js?bust=1545012687057:281:54)
    at Property._notifyListeners (https://bayes.colorado.edu/continuous-testing/snapshot-1544980472044/axon/js/Property.js?bust=1545012687057:288:29)
id: Bayes Chrome
Approximately 12/16/2018, 10:14:32 AM
projectile-motion : fuzz : require.js-canvas : run
Uncaught Error: Assertion failed: mapped to value that is wider than the NumberDisplay background
Error: Assertion failed: mapped to value that is wider than the NumberDisplay background
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1544980472044/assert/js/assert.js:22:13)
    at Array.numberObserver (https://bayes.colorado.edu/continuous-testing/snapshot-1544980472044/scenery-phet/js/NumberDisplay.js?bust=1545028088558:107:17)
    at Emitter.emit3 (https://bayes.colorado.edu/continuous-testing/snapshot-1544980472044/axon/js/Emitter.js?bust=1545028088558:281:54)
    at NumberProperty._notifyListeners (https://bayes.colorado.edu/continuous-testing/snapshot-1544980472044/axon/js/Property.js?bust=1545028088558:288:29)
    at NumberProperty.setValueAndNotifyListeners (https://bayes.colorado.edu/continuous-testing/snapshot-1544980472044/axon/js/Property.js?bust=1545028088558:270:14)
    at NumberProperty.set (https://bayes.colorado.edu/continuous-testing/snapshot-1544980472044/axon/js/Property.js?bust=1545028088558:203:16)
    at NumberProperty.set (https://bayes.colorado.edu/continuous-testing/snapshot-1544980472044/axon/js/NumberProperty.js?bust=1545028088558:84:30)
    at LabModel.setProjectileParameters (https://bayes.colorado.edu/continuous-testing/snapshot-1544980472044/projectile-motion/js/lab/model/LabModel.js?bust=1545028088558:113:37)
    at Emitter.emit3 (https://bayes.colorado.edu/continuous-testing/snapshot-1544980472044/axon/js/Emitter.js?bust=1545028088558:281:54)
    at Property._notifyListeners (https://bayes.colorado.edu/continuous-testing/snapshot-1544980472044/axon/js/Property.js?bust=1545028088558:288:29)
id: Bayes Chrome
Approximately 12/16/2018, 10:14:32 AM
projectile-motion : fuzz : require.js-canvas : run
Uncaught Error: Assertion failed: mapped to value that is wider than the NumberDisplay background
Error: Assertion failed: mapped to value that is wider than the NumberDisplay background
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1544980472044/assert/js/assert.js:22:13)
    at Array.numberObserver (https://bayes.colorado.edu/continuous-testing/snapshot-1544980472044/scenery-phet/js/NumberDisplay.js?bust=1545051052453:107:17)
    at Emitter.emit3 (https://bayes.colorado.edu/continuous-testing/snapshot-1544980472044/axon/js/Emitter.js?bust=1545051052453:281:54)
    at NumberProperty._notifyListeners (https://bayes.colorado.edu/continuous-testing/snapshot-1544980472044/axon/js/Property.js?bust=1545051052453:288:29)
    at NumberProperty.setValueAndNotifyListeners (https://bayes.colorado.edu/continuous-testing/snapshot-1544980472044/axon/js/Property.js?bust=1545051052453:270:14)
    at NumberProperty.set (https://bayes.colorado.edu/continuous-testing/snapshot-1544980472044/axon/js/Property.js?bust=1545051052453:203:16)
    at NumberProperty.set (https://bayes.colorado.edu/continuous-testing/snapshot-1544980472044/axon/js/NumberProperty.js?bust=1545051052453:84:30)
    at LabModel.setProjectileParameters (https://bayes.colorado.edu/continuous-testing/snapshot-1544980472044/projectile-motion/js/lab/model/LabModel.js?bust=1545051052453:108:37)
    at Emitter.emit3 (https://bayes.colorado.edu/continuous-testing/snapshot-1544980472044/axon/js/Emitter.js?bust=1545051052453:281:54)
    at Property._notifyListeners (https://bayes.colorado.edu/continuous-testing/snapshot-1544980472044/axon/js/Property.js?bust=1545051052453:288:29)
id: Bayes Chrome
Approximately 12/16/2018, 10:14:32 AM
projectile-motion : fuzz : require.js-canvas : run
Uncaught Error: Assertion failed: mapped to value that is wider than the NumberDisplay background
Error: Assertion failed: mapped to value that is wider than the NumberDisplay background
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1544980472044/assert/js/assert.js:22:13)
    at Array.numberObserver (https://bayes.colorado.edu/continuous-testing/snapshot-1544980472044/scenery-phet/js/NumberDisplay.js?bust=1545059591661:107:17)
    at Emitter.emit3 (https://bayes.colorado.edu/continuous-testing/snapshot-1544980472044/axon/js/Emitter.js?bust=1545059591661:281:54)
    at NumberProperty._notifyListeners (https://bayes.colorado.edu/continuous-testing/snapshot-1544980472044/axon/js/Property.js?bust=1545059591661:288:29)
    at NumberProperty.setValueAndNotifyListeners (https://bayes.colorado.edu/continuous-testing/snapshot-1544980472044/axon/js/Property.js?bust=1545059591661:270:14)
    at NumberProperty.set (https://bayes.colorado.edu/continuous-testing/snapshot-1544980472044/axon/js/Property.js?bust=1545059591661:203:16)
    at NumberProperty.set (https://bayes.colorado.edu/continuous-testing/snapshot-1544980472044/axon/js/NumberProperty.js?bust=1545059591661:84:30)
    at LabModel.setProjectileParameters (https://bayes.colorado.edu/continuous-testing/snapshot-1544980472044/projectile-motion/js/lab/model/LabModel.js?bust=1545059591661:113:37)
    at Emitter.emit3 (https://bayes.colorado.edu/continuous-testing/snapshot-1544980472044/axon/js/Emitter.js?bust=1545059591661:281:54)
    at Property._notifyListeners (https://bayes.colorado.edu/continuous-testing/snapshot-1544980472044/axon/js/Property.js?bust=1545059591661:288:29)
id: Bayes Chrome
Approximately 12/16/2018, 10:14:32 AM
projectile-motion : xss-fuzz : run
Uncaught Error: Assertion failed: mapped to value that is wider than the NumberDisplay background
Error: Assertion failed: mapped to value that is wider than the NumberDisplay background
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1544980472044/assert/js/assert.js:22:13)
    at Array.numberObserver (https://bayes.colorado.edu/continuous-testing/snapshot-1544980472044/scenery-phet/js/NumberDisplay.js?bust=1544986830932:107:17)
    at Emitter.emit3 (https://bayes.colorado.edu/continuous-testing/snapshot-1544980472044/axon/js/Emitter.js?bust=1544986830932:281:54)
    at NumberProperty._notifyListeners (https://bayes.colorado.edu/continuous-testing/snapshot-1544980472044/axon/js/Property.js?bust=1544986830932:288:29)
    at NumberProperty.setValueAndNotifyListeners (https://bayes.colorado.edu/continuous-testing/snapshot-1544980472044/axon/js/Property.js?bust=1544986830932:270:14)
    at NumberProperty.set (https://bayes.colorado.edu/continuous-testing/snapshot-1544980472044/axon/js/Property.js?bust=1544986830932:203:16)
    at NumberProperty.set (https://bayes.colorado.edu/continuous-testing/snapshot-1544980472044/axon/js/NumberProperty.js?bust=1544986830932:84:30)
    at LabModel.setProjectileParameters (https://bayes.colorado.edu/continuous-testing/snapshot-1544980472044/projectile-motion/js/lab/model/LabModel.js?bust=1544986830932:113:37)
    at Emitter.emit3 (https://bayes.colorado.edu/continuous-testing/snapshot-1544980472044/axon/js/Emitter.js?bust=1544986830932:281:54)
    at Property._notifyListeners (https://bayes.colorado.edu/continuous-testing/snapshot-1544980472044/axon/js/Property.js?bust=1544986830932:288:29)
id: Bayes Chrome
Approximately 12/16/2018, 10:14:32 AM
projectile-motion : xss-fuzz : run
Uncaught Error: Assertion failed: mapped to value that is wider than the NumberDisplay background
Error: Assertion failed: mapped to value that is wider than the NumberDisplay background
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1544980472044/assert/js/assert.js:22:13)
    at Array.numberObserver (https://bayes.colorado.edu/continuous-testing/snapshot-1544980472044/scenery-phet/js/NumberDisplay.js?bust=1545018470184:107:17)
    at Emitter.emit3 (https://bayes.colorado.edu/continuous-testing/snapshot-1544980472044/axon/js/Emitter.js?bust=1545018470184:281:54)
    at NumberProperty._notifyListeners (https://bayes.colorado.edu/continuous-testing/snapshot-1544980472044/axon/js/Property.js?bust=1545018470184:288:29)
    at NumberProperty.setValueAndNotifyListeners (https://bayes.colorado.edu/continuous-testing/snapshot-1544980472044/axon/js/Property.js?bust=1545018470184:270:14)
    at NumberProperty.set (https://bayes.colorado.edu/continuous-testing/snapshot-1544980472044/axon/js/Property.js?bust=1545018470184:203:16)
    at NumberProperty.set (https://bayes.colorado.edu/continuous-testing/snapshot-1544980472044/axon/js/NumberProperty.js?bust=1545018470184:84:30)
    at LabModel.setProjectileParameters (https://bayes.colorado.edu/continuous-testing/snapshot-1544980472044/projectile-motion/js/lab/model/LabModel.js?bust=1545018470184:108:37)
    at Emitter.emit3 (https://bayes.colorado.edu/continuous-testing/snapshot-1544980472044/axon/js/Emitter.js?bust=1545018470184:281:54)
    at Property._notifyListeners (https://bayes.colorado.edu/continuous-testing/snapshot-1544980472044/axon/js/Property.js?bust=1545018470184:288:29)
id: Bayes Chrome
Approximately 12/16/2018, 10:14:32 AM
projectile-motion : xss-fuzz : run
Uncaught Error: Assertion failed: mapped to value that is wider than the NumberDisplay background
Error: Assertion failed: mapped to value that is wider than the NumberDisplay background
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1544980472044/assert/js/assert.js:22:13)
    at Array.numberObserver (https://bayes.colorado.edu/continuous-testing/snapshot-1544980472044/scenery-phet/js/NumberDisplay.js?bust=1545025784342:107:17)
    at Emitter.emit3 (https://bayes.colorado.edu/continuous-testing/snapshot-1544980472044/axon/js/Emitter.js?bust=1545025784342:281:54)
    at NumberProperty._notifyListeners (https://bayes.colorado.edu/continuous-testing/snapshot-1544980472044/axon/js/Property.js?bust=1545025784342:288:29)
    at NumberProperty.setValueAndNotifyListeners (https://bayes.colorado.edu/continuous-testing/snapshot-1544980472044/axon/js/Property.js?bust=1545025784342:270:14)
    at NumberProperty.set (https://bayes.colorado.edu/continuous-testing/snapshot-1544980472044/axon/js/Property.js?bust=1545025784342:203:16)
    at NumberProperty.set (https://bayes.colorado.edu/continuous-testing/snapshot-1544980472044/axon/js/NumberProperty.js?bust=1545025784342:84:30)
    at LabModel.setProjectileParameters (https://bayes.colorado.edu/continuous-testing/snapshot-1544980472044/projectile-motion/js/lab/model/LabModel.js?bust=1545025784342:108:37)
    at Emitter.emit3 (https://bayes.colorado.edu/continuous-testing/snapshot-1544980472044/axon/js/Emitter.js?bust=1545025784342:281:54)
    at Property._notifyListeners (https://bayes.colorado.edu/continuous-testing/snapshot-1544980472044/axon/js/Property.js?bust=1545025784342:288:29)
id: Bayes Chrome
Approximately 12/16/2018, 10:14:32 AM
projectile-motion : xss-fuzz : run
Uncaught Error: Assertion failed: mapped to value that is wider than the NumberDisplay background
Error: Assertion failed: mapped to value that is wider than the NumberDisplay background
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1544980472044/assert/js/assert.js:22:13)
    at Array.numberObserver (https://bayes.colorado.edu/continuous-testing/snapshot-1544980472044/scenery-phet/js/NumberDisplay.js?bust=1545046408356:107:17)
    at Emitter.emit3 (https://bayes.colorado.edu/continuous-testing/snapshot-1544980472044/axon/js/Emitter.js?bust=1545046408356:281:54)
    at NumberProperty._notifyListeners (https://bayes.colorado.edu/continuous-testing/snapshot-1544980472044/axon/js/Property.js?bust=1545046408356:288:29)
    at NumberProperty.setValueAndNotifyListeners (https://bayes.colorado.edu/continuous-testing/snapshot-1544980472044/axon/js/Property.js?bust=1545046408356:270:14)
    at NumberProperty.set (https://bayes.colorado.edu/continuous-testing/snapshot-1544980472044/axon/js/Property.js?bust=1545046408356:203:16)
    at NumberProperty.set (https://bayes.colorado.edu/continuous-testing/snapshot-1544980472044/axon/js/NumberProperty.js?bust=1545046408356:84:30)
    at LabModel.setProjectileParameters (https://bayes.colorado.edu/continuous-testing/snapshot-1544980472044/projectile-motion/js/lab/model/LabModel.js?bust=1545046408356:108:37)
    at Emitter.emit3 (https://bayes.colorado.edu/continuous-testing/snapshot-1544980472044/axon/js/Emitter.js?bust=1545046408356:281:54)
    at Property._notifyListeners (https://bayes.colorado.edu/continuous-testing/snapshot-1544980472044/axon/js/Property.js?bust=1545046408356:288:29)
id: Bayes Chrome
Approximately 12/16/2018, 10:14:32 AM
```

**Comment by jessegreenberg** [comment]
This should be fixed after recent changes for https://github.com/phetsims/scenery-phet/issues/440. If this is gone in the next round on CT Ill close this issue.

**Comment by jessegreenberg** [comment]
Its gone on later CT testing so feels safe to close.
