### ISSUE TITLE
CT No such file or directory 

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/projectile-motion#174]
```
projectile-motion : build : phet
Failure to grunt snapshot-1553634747015/projectile-motion:
Running "lint-all" task

Running "report-media" task

Running "clean" task

Running "build" task
Building runnable repository (projectile-motion, brands: phet)
Building brand: phet
Fatal error: Perennial task failed:
Error: Error: Error: ENOENT: no such file or directory, open '/data/share/phet/continuous-testing/snapshot-1553634747015/projectile-motion/js/TWIXT/Animation.js'
In module tree:
    projectile-motion-main
      PROJECTILE_MOTION/drag/DragScreen
        PROJECTILE_MOTION/drag/view/DragScreenView
          PROJECTILE_MOTION/common/view/ProjectileMotionScreenView
            PROJECTILE_MOTION/common/view/TargetNode

  at /data/share/phet/continuous-testing/snapshot-1553634747015/chipper/js/grunt/requireBuild.js:107:15
  at /data/share/phet/continuous-testing/snapshot-1553634747015/chipper/node_modules/requirejs/bin/r.js:3059:39
  at /data/share/phet/continuous-testing/snapshot-1553634747015/chipper/node_modules/requirejs/bin/r.js:2999:25
  at Function.prim.nextTick (/data/share/phet/continuous-testing/snapshot-1553634747015/chipper/node_modules/requirejs/bin/r.js:28083:9)
  at Object.errback (/data/share/phet/continuous-testing/snapshot-1553634747015/chipper/node_modules/requirejs/bin/r.js:2998:26)
  at Object.callback (/data/share/phet/continuous-testing/snapshot-1553634747015/chipper/node_modules/requirejs/bin/r.js:2984:23)
  at Object.then (/data/share/phet/continuous-testing/snapshot-1553634747015/chipper/node_modules/requirejs/bin/r.js:3038:23)
  at runBuild (/data/share/phet/continuous-testing/snapshot-1553634747015/chipper/node_modules/requirejs/bin/r.js:30302:48)
  at Object.execCb (/data/share/phet/continuous-testing/snapshot-1553634747015/chipper/node_modules/requirejs/bin/r.js:1946:33)
  at Module.check (/data/share/phet/continuous-testing/snapshot-1553634747015/chipper/node_modules/requirejs/bin/r.js:1133:51)
  at Module.<anonymous> (/data/share/phet/continuous-testing/snapshot-1553634747015/chipper/node_modules/requirejs/bin/r.js:1389:34)
  at /data/share/phet/continuous-testing/snapshot-1553634747015/chipper/node_modules/requirejs/bin/r.js:384:23
  at /data/share/phet/continuous-testing/snapshot-1553634747015/chipper/node_modules/requirejs/bin/r.js:1439:21
  at each (/data/share/phet/continuous-testing/snapshot-1553634747015/chipper/node_modules/requirejs/bin/r.js:309:31)
  at Module.emit (/data/share/phet/continuous-testing/snapshot-1553634747015/chipper/node_modules/requirejs/bin/r.js:1438:17)
  at Module.check (/data/share/phet/continuous-testing/snapshot-1553634747015/chipper/node_modules/requirejs/bin/r.js:1188:30)
  at Module.enable (/data/share/phet/continuous-testing/snapshot-1553634747015/chipper/node_modules/requirejs/bin/r.js:1426:22)
  at Module.init (/data/share/phet/continuous-testing/snapshot-1553634747015/chipper/node_modules/requirejs/bin/r.js:1038:26)
  at Module.<anonymous> (/data/share/phet/continuous-testing/snapshot-1553634747015/chipper/node_modules/requirejs/bin/r.js:1264:30)
  at /data/share/phet/continuous-testing/snapshot-1553634747015/chipper/node_modules/requirejs/bin/r.js:384:23
  at /data/share/phet/continuous-testing/snapshot-1553634747015/chipper/node_modules/requirejs/bin/r.js:2697:17
  at Object.execCb (/data/share/phet/continuous-testing/snapshot-1553634747015/chipper/node_modules/requirejs/bin/r.js:1946:33)
  at Module.check (/data/share/phet/continuous-testing/snapshot-1553634747015/chipper/node_modules/requirejs/bin/r.js:1133:51)
  at Module.enable (/data/share/phet/continuous-testing/snapshot-1553634747015/chipper/node_modules/requirejs/bin/r.js:1426:22)
  at Module.init (/data/share/phet/continuous-testing/snapshot-1553634747015/chipper/node_modules/requirejs/bin/r.js:1038:26)
  at /data/share/phet/continuous-testing/snapshot-1553634747015/chipper/node_modules/requirejs/bin/r.js:1710:36
  at _combinedTickCallback (internal/process/next_tick.js:132:7)
  at process._tickCallback (internal/process/next_tick.js:181:9)

Full Error details:
{}


Approximately 3/26/2019, 3:12:27 PM
projectile-motion : fuzz : require.js-canvas : load
Query: brand=phet&ea&fuzz&rootRenderer=canvas&memoryLimit=1000
Uncaught Error: Script error for: TWIXT/Animation
http://requirejs.org/docs/errors.html#scripterror
Error: Script error for: TWIXT/Animation
http://requirejs.org/docs/errors.html#scripterror
    at makeError (https://bayes.colorado.edu/continuous-testing/snapshot-1553634747015/sherpa/lib/require-2.1.11.js:166:13)
    at HTMLScriptElement.onScriptError (https://bayes.colorado.edu/continuous-testing/snapshot-1553634747015/sherpa/lib/require-2.1.11.js:1681:26)
id: Bayes Chrome
Approximately 3/26/2019, 3:12:27 PM
projectile-motion : fuzz : require.js-canvas : load
Query: brand=phet&ea&fuzz&rootRenderer=canvas&memoryLimit=1000
Uncaught Error: Script error for: TWIXT/Easing
http://requirejs.org/docs/errors.html#scripterror
Error: Script error for: TWIXT/Easing
http://requirejs.org/docs/errors.html#scripterror
    at makeError (https://bayes.colorado.edu/continuous-testing/snapshot-1553634747015/sherpa/lib/require-2.1.11.js:166:13)
    at HTMLScriptElement.onScriptError (https://bayes.colorado.edu/continuous-testing/snapshot-1553634747015/sherpa/lib/require-2.1.11.js:1681:26)
id: Bayes Chrome
Approximately 3/26/2019, 3:12:27 PM
projectile-motion : fuzz : require.js-canvas : run
Query: brand=phet&ea&fuzz&rootRenderer=canvas&memoryLimit=1000
Uncaught Error: Script error for: TWIXT/Animation
http://requirejs.org/docs/errors.html#scripterror
Error: Script error for: TWIXT/Animation
http://requirejs.org/docs/errors.html#scripterror
    at makeError (https://bayes.colorado.edu/continuous-testing/snapshot-1553634747015/sherpa/lib/require-2.1.11.js:166:13)
    at HTMLScriptElement.onScriptError (https://bayes.colorado.edu/continuous-testing/snapshot-1553634747015/sherpa/lib/require-2.1.11.js:1681:26)
id: Bayes Chrome
Approximately 3/26/2019, 3:12:27 PM
projectile-motion : fuzz : require.js-canvas : run
Query: brand=phet&ea&fuzz&rootRenderer=canvas&memoryLimit=1000
Uncaught Error: Script error for: TWIXT/Easing
http://requirejs.org/docs/errors.html#scripterror
Error: Script error for: TWIXT/Easing
http://requirejs.org/docs/errors.html#scripterror
    at makeError (https://bayes.colorado.edu/continuous-testing/snapshot-1553634747015/sherpa/lib/require-2.1.11.js:166:13)
    at HTMLScriptElement.onScriptError (https://bayes.colorado.edu/continuous-testing/snapshot-1553634747015/sherpa/lib/require-2.1.11.js:1681:26)
id: Bayes Chrome
Approximately 3/26/2019, 3:12:27 PM
```

May relate to https://github.com/phetsims/gene-expression-essentials/issues/125

**Comment by jbphet** [comment]
Fixed by @samreid in 3916ffb7e29ecd73cdb1cb7d091104446ab38a23, closing.
