### ISSUE TITLE
CT cannot normalize a zero-magnitude vector

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/projectile-motion#234]
```
projectile-motion : fuzz : built-phet-io
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1601845816475/projectile-motion/build/phet-io/projectile-motion_all_phet-io.html?continuousTest=%7B%22test%22%3A%5B%22projectile-motion%22%2C%22fuzz%22%2C%22built-phet-io%22%5D%2C%22snapshotName%22%3A%22snapshot-1601845816475%22%2C%22timestamp%22%3A1601887484638%7D&fuzz&memoryLimit=1000&phetioStandalone
Query: fuzz&memoryLimit=1000&phetioStandalone
Uncaught Error: Cannot normalize a zero-magnitude vector
Error: Cannot normalize a zero-magnitude vector
at l.normalized (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1601845816475/projectile-motion/build/phet-io/projectile-motion_all_phet-io.html?continuousTest=%7B%22test%22%3A%5B%22projectile-motion%22%2C%22fuzz%22%2C%22built-phet-io%22%5D%2C%22snapshotName%22%3A%22snapshot-1601845816475%22%2C%22timestamp%22%3A1601887484638%7D&fuzz&memoryLimit=1000&phetioStandalone:846:15282)
at qt.getStartTangent (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1601845816475/projectile-motion/build/phet-io/projectile-motion_all_phet-io.html?continuousTest=%7B%22test%22%3A%5B%22projectile-motion%22%2C%22fuzz%22%2C%22built-phet-io%22%5D%2C%22snapshotName%22%3A%22snapshot-1601845816475%22%2C%22timestamp%22%3A1601887484638%7D&fuzz&memoryLimit=1000&phetioStandalone:846:174574)
at qt.get startTangent [as startTangent] (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1601845816475/projectile-motion/build/phet-io/projectile-motion_all_phet-io.html?continuousTest=%7B%22test%22%3A%5B%22projectile-motion%22%2C%22fuzz%22%2C%22built-phet-io%22%5D%2C%22snapshotName%22%3A%22snapshot-1601845816475%22%2C%22timestamp%22%3A1601887484638%7D&fuzz&memoryLimit=1000&phetioStandalone:846:174634)
at qt.areStrokedBoundsDilated (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1601845816475/projectile-motion/build/phet-io/projectile-motion_all_phet-io.html?continuousTest=%7B%22test%22%3A%5B%22projectile-motion%22%2C%22fuzz%22%2C%22built-phet-io%22%5D%2C%22snapshotName%22%3A%22snapshot-1601845816475%22%2C%22timestamp%22%3A1601887484638%7D&fuzz&memoryLimit=1000&phetioStandalone:846:168025)
at Ye.getStrokedBounds (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1601845816475/projectile-motion/build/phet-io/projectile-motion_all_phet-io.html?continuousTest=%7B%22test%22%3A%5B%22projectile-motion%22%2C%22fuzz%22%2C%22built-phet-io%22%5D%2C%22snapshotName%22%3A%22snapshot-1601845816475%22%2C%22timestamp%22%3A1601887484638%7D&fuzz&memoryLimit=1000&phetioStandalone:846:280004)
at Sf.computeShapeBounds (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1601845816475/projectile-motion/build/phet-io/projectile-motion_all_phet-io.html?continuousTest=%7B%22test%22%3A%5B%22projectile-motion%22%2C%22fuzz%22%2C%22built-phet-io%22%5D%2C%22snapshotName%22%3A%22snapshot-1601845816475%22%2C%22timestamp%22%3A1601887484638%7D&fuzz&memoryLimit=1000&phetioStandalone:846:572217)
at Sf.updateSelfBounds (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1601845816475/projectile-motion/build/phet-io/projectile-motion_all_phet-io.html?continuousTest=%7B%22test%22%3A%5B%22projectile-motion%22%2C%22fuzz%22%2C%22built-phet-io%22%5D%2C%22snapshotName%22%3A%22snapshot-1601845816475%22%2C%22timestamp%22%3A1601887484638%7D&fuzz&memoryLimit=1000&phetioStandalone:846:571604)
at Sf.validateSelfBounds (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1601845816475/projectile-motion/build/phet-io/projectile-motion_all_phet-io.html?continuousTest=%7B%22test%22%3A%5B%22projectile-motion%22%2C%22fuzz%22%2C%22built-phet-io%22%5D%2C%22snapshotName%22%3A%22snapshot-1601845816475%22%2C%22timestamp%22%3A1601887484638%7D&fuzz&memoryLimit=1000&phetioStandalone:846:455131)
at Sf.validateBounds (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1601845816475/projectile-motion/build/phet-io/projectile-motion_all_phet-io.html?continuousTest=%7B%22test%22%3A%5B%22projectile-motion%22%2C%22fuzz%22%2C%22built-phet-io%22%5D%2C%22snapshotName%22%3A%22snapshot-1601845816475%22%2C%22timestamp%22%3A1601887484638%7D&fuzz&memoryLimit=1000&phetioStandalone:846:455280)
at _P.validateBounds (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1601845816475/projectile-motion/build/phet-io/projectile-motion_all_phet-io.html?continuousTest=%7B%22test%22%3A%5B%22projectile-motion%22%2C%22fuzz%22%2C%22built-phet-io%22%5D%2C%22snapshotName%22%3A%22snapshot-1601845816475%22%2C%22timestamp%22%3A1601887484638%7D&fuzz&memoryLimit=1000&phetioStandalone:846:455514)
id: Bayes Chrome
Snapshot from 10/4/2020, 3:10:16 PM

----------------------------------

projectile-motion : phet-io-state-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1601845816475/phet-io-wrappers/state/?sim=projectile-motion&phetioDebug&fuzz&wrapperContinuousTest=%7B%22test%22%3A%5B%22projectile-motion%22%2C%22phet-io-state-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1601845816475%22%2C%22timestamp%22%3A1601862446304%7D
Uncaught Error: Uncaught Error: Assertion failed: timeToGround: NaN, previousPoint.velocity: Vector2(0, 0), previousPoint.acceleration: Vector2(0, 0), fromIf: true
Error: Assertion failed: timeToGround: NaN, previousPoint.velocity: Vector2(0, 0), previousPoint.acceleration: Vector2(0, 0), fromIf: true
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1601845816475/assert/js/assert.js:22:13)
at Trajectory.step (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1601845816475/projectile-motion/js/common/model/Trajectory.js:244:19)
at IntroModel.stepModelElements (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1601845816475/projectile-motion/js/common/model/ProjectileMotionModel.js:328:44)
at EventTimer.step (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1601845816475/phet-core/js/EventTimer.js:123:12)
at IntroModel.step (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1601845816475/projectile-motion/js/common/model/ProjectileMotionModel.js:316:23)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1601845816475/joist/js/Sim.js:296:22
at Action.execute (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1601845816475/axon/js/Action.js:225:18)
at Sim.stepSimulation (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1601845816475/joist/js/Sim.js:974:31)
at Sim.stepOneFrame (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1601845816475/joist/js/Sim.js:964:12)
at Sim.runAnimationLoop (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1601845816475/joist/js/Sim.js:942:12)
id: Bayes Chrome
Snapshot from 10/4/2020, 3:10:16 PM
```

**Comment by jbphet** [comment]
I was talking with @zepumph, and he said that he thought this issue might be due to the phet-io work that was done on this sim a while back, so I'm assigning to him.  @zepumph - feel free to hit it back into my court if it makes sense to do so.

**Comment by marlitas** [comment]
This error is not showing in the last 40 columns of CT and has not been worked on for over 2 years. Closing as stale.
