### ISSUE TITLE
CT Build failed with status code 1

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/projectile-motion#236]
```
projectile-motion : build
Build failed with status code 1:
Running "report-media" task

Running "clean" task

Running "build" task
Building runnable repository (projectile-motion, brands: phet, phet-io)
Building brand: phet
>> Webpack build complete: 4658ms
>> Production minification complete: 30177ms (2121038 bytes)
>> Debug minification complete: 0ms (6286191 bytes)
Building brand: phet-io
>> Webpack build complete: 3635ms
>> Production minification complete: 27134ms (2135420 bytes)
>> Debug minification complete: 26668ms (2394165 bytes)
>> No client guides found at ../phet-io-client-guides/projectile-motion/, no guides being built.
Fatal error: Perennial task failed: Error: TypeError: Bb.createLayoutFunction4 is not a constructor
at Object.layoutFunction (http://localhost:45289/projectile-motion/build/phet-io/projectile-motion_all_phet-io.html?ea&brand=phet-io&phetioStandalone&phetioPrintAPI:846:1736030)
at new xb (http://localhost:45289/projectile-motion/build/phet-io/projectile-motion_all_phet-io.html?ea&brand=phet-io&phetioStandalone&phetioPrintAPI:846:1454335)
at new VV (http://localhost:45289/projectile-motion/build/phet-io/projectile-motion_all_phet-io.html?ea&brand=phet-io&phetioStandalone&phetioPrintAPI:846:1735636)
at new iC (http://localhost:45289/projectile-motion/build/phet-io/projectile-motion_all_phet-io.html?ea&brand=phet-io&phetioStandalone&phetioPrintAPI:846:1755422)
at sC.createView (http://localhost:45289/projectile-motion/build/phet-io/projectile-motion_all_phet-io.html?ea&brand=phet-io&phetioStandalone&phetioPrintAPI:846:1755850)
at sC.initializeView (http://localhost:45289/projectile-motion/build/phet-io/projectile-motion_all_phet-io.html?ea&brand=phet-io&phetioStandalone&phetioPrintAPI:846:781904)
at Array.<anonymous> (http://localhost:45289/projectile-motion/build/phet-io/projectile-motion_all_phet-io.html?ea&brand=phet-io&phetioStandalone&phetioPrintAPI:846:952194)
at http://localhost:45289/projectile-motion/build/phet-io/projectile-motion_all_phet-io.html?ea&brand=phet-io&phetioStandalone&phetioPrintAPI:846:952291

Browserslist: caniuse-lite is outdated. Please run:
npx browserslist@latest --update-db
Snapshot from 10/15/2020, 3:32:28 PM

----------------------------------

projectile-motion : fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1602797548336/projectile-motion/projectile-motion_en.html?continuousTest=%7B%22test%22%3A%5B%22projectile-motion%22%2C%22fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1602797548336%22%2C%22timestamp%22%3A1602802340273%7D&brand=phet&ea&fuzz&memoryLimit=1000
Query: brand=phet&ea&fuzz&memoryLimit=1000
Uncaught TypeError: NumberControl.createLayoutFunction4 is not a constructor
TypeError: NumberControl.createLayoutFunction4 is not a constructor
at Object.dragLayoutFunction [as layoutFunction] (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1602797548336/projectile-motion/js/drag/view/DragProjectileControlPanel.js:153:14)
at new NumberControl (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1602797548336/scenery-phet/js/NumberControl.js:354:15)
at new DragProjectileControlPanel (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1602797548336/projectile-motion/js/drag/view/DragProjectileControlPanel.js:159:32)
at new DragScreenView (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1602797548336/projectile-motion/js/drag/view/DragScreenView.js:29:7)
at DragScreen.createView (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1602797548336/projectile-motion/js/drag/DragScreen.js:37:34)
at DragScreen.initializeView (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1602797548336/joist/js/Screen.js:250:23)
at Array.<anonymous> (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1602797548336/joist/js/Sim.js:855:16)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1602797548336/joist/js/Sim.js:863:25
id: Bayes Chrome
Snapshot from 10/15/2020, 3:32:28 PM

----------------------------------

projectile-motion : phet-io-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1602797548336/projectile-motion/projectile-motion_en.html?continuousTest=%7B%22test%22%3A%5B%22projectile-motion%22%2C%22phet-io-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1602797548336%22%2C%22timestamp%22%3A1602801149435%7D&ea&brand=phet-io&phetioStandalone&fuzz&memoryLimit=1000
Query: ea&brand=phet-io&phetioStandalone&fuzz&memoryLimit=1000
Uncaught TypeError: NumberControl.createLayoutFunction4 is not a constructor
TypeError: NumberControl.createLayoutFunction4 is not a constructor
at Object.dragLayoutFunction [as layoutFunction] (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1602797548336/projectile-motion/js/drag/view/DragProjectileControlPanel.js:153:14)
at new NumberControl (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1602797548336/scenery-phet/js/NumberControl.js:354:15)
at new DragProjectileControlPanel (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1602797548336/projectile-motion/js/drag/view/DragProjectileControlPanel.js:159:32)
at new DragScreenView (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1602797548336/projectile-motion/js/drag/view/DragScreenView.js:29:7)
at DragScreen.createView (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1602797548336/projectile-motion/js/drag/DragScreen.js:37:34)
at DragScreen.initializeView (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1602797548336/joist/js/Screen.js:250:23)
at Array.<anonymous> (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1602797548336/joist/js/Sim.js:855:16)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1602797548336/joist/js/Sim.js:863:25
id: Bayes Chrome
Snapshot from 10/15/2020, 3:32:28 PM

----------------------------------

projectile-motion : phet-io-state-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1602797548336/phet-io-wrappers/state/?sim=projectile-motion&phetioDebug&fuzz&wrapperContinuousTest=%7B%22test%22%3A%5B%22projectile-motion%22%2C%22phet-io-state-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1602797548336%22%2C%22timestamp%22%3A1602802532899%7D
Uncaught Error: Uncaught TypeError: NumberControl.createLayoutFunction4 is not a constructor
TypeError: NumberControl.createLayoutFunction4 is not a constructor
at Object.dragLayoutFunction [as layoutFunction] (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1602797548336/projectile-motion/js/drag/view/DragProjectileControlPanel.js:153:14)
at new NumberControl (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1602797548336/scenery-phet/js/NumberControl.js:354:15)
at new DragProjectileControlPanel (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1602797548336/projectile-motion/js/drag/view/DragProjectileControlPanel.js:159:32)
at new DragScreenView (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1602797548336/projectile-motion/js/drag/view/DragScreenView.js:29:7)
at DragScreen.createView (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1602797548336/projectile-motion/js/drag/DragScreen.js:37:34)
at DragScreen.initializeView (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1602797548336/joist/js/Screen.js:250:23)
at Array.<anonymous> (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1602797548336/joist/js/Sim.js:855:16)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1602797548336/joist/js/Sim.js:863:25
id: Bayes Chrome
Snapshot from 10/15/2020, 3:32:28 PM

----------------------------------

projectile-motion : phet-io-studio-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1602797548336/studio/?sim=projectile-motion&phetioDebug&fuzz&wrapperContinuousTest=%7B%22test%22%3A%5B%22projectile-motion%22%2C%22phet-io-studio-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1602797548336%22%2C%22timestamp%22%3A1602798863975%7D
Uncaught Error: Uncaught TypeError: NumberControl.createLayoutFunction4 is not a constructor
TypeError: NumberControl.createLayoutFunction4 is not a constructor
at Object.dragLayoutFunction [as layoutFunction] (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1602797548336/projectile-motion/js/drag/view/DragProjectileControlPanel.js:153:14)
at new NumberControl (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1602797548336/scenery-phet/js/NumberControl.js:354:15)
at new DragProjectileControlPanel (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1602797548336/projectile-motion/js/drag/view/DragProjectileControlPanel.js:159:32)
at new DragScreenView (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1602797548336/projectile-motion/js/drag/view/DragScreenView.js:29:7)
at DragScreen.createView (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1602797548336/projectile-motion/js/drag/DragScreen.js:37:34)
at DragScreen.initializeView (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1602797548336/joist/js/Screen.js:250:23)
at Array.<anonymous> (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1602797548336/joist/js/Sim.js:855:16)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1602797548336/joist/js/Sim.js:863:25
id: Bayes Chrome
Snapshot from 10/15/2020, 3:32:28 PM

----------------------------------

projectile-motion : phet-io-wrappers-tests : assert
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1602797548336/phet-io-wrappers/phet-io-wrappers-tests.html?sim=projectile-motion&phetioDebug
3 out of 4 tests passed. 1 failed.
SimTests: projectile-motion: iframe api failed:
Uncaught Error: Uncaught TypeError: NumberControl.createLayoutFunction4 is not a constructor
TypeError: NumberControl.createLayoutFunction4 is not a constructor
at Object.dragLayoutFunction [as layoutFunction] (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1602797548336/projectile-motion/js/drag/view/DragProjectileControlPanel.js:153:14)
at new NumberControl (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1602797548336/scenery-phet/js/NumberControl.js:354:15)
at new DragProjectileControlPanel (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1602797548336/projectile-motion/js/drag/view/DragProjectileControlPanel.js:159:32)
at new DragScreenView (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1602797548336/projectile-motion/js/drag/view/DragScreenView.js:29:7)
at DragScreen.createView (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1602797548336/projectile-motion/js/drag/DragScreen.js:37:34)
at DragScreen.initializeView (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1602797548336/joist/js/Screen.js:250:23)
at Array.<anonymous> (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1602797548336/joist/js/Sim.js:855:16)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1602797548336/joist/js/Sim.js:863:25

Did not complete in 200000ms, may not have completed all tests
id: Bayes Chrome
Snapshot from 10/15/2020, 3:32:28 PM
```

**Comment by jbphet** [comment]
It looks like this was a problem with NumberControl, which was being modified for https://github.com/phetsims/tasks/issues/1044. 
 CT looks clear for the last several runs, and a fresh checkout built fine in my local workspace, so I'm going to assume that the problem has been corrected and close this.
