### ISSUE TITLE
CT: AssertionError [ERR_ASSERTION] [ERR_ASSERTION]: full api expected

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/projectile-motion#264]
```
projectile-motion : build
Build failed with status code 1:
Running "report-media" task

Running "clean" task

Running "build" task
Building runnable repository (projectile-motion, brands: phet, phet-io)
Building brand: phet
>> Webpack build complete: 4468ms
>> Production minification complete: 28984ms (2114185 bytes)
>> Debug minification complete: 1ms (6384119 bytes)
Building brand: phet-io
>> Webpack build complete: 3331ms
>> Production minification complete: 23298ms (2134931 bytes)
>> Debug minification complete: 22965ms (2408093 bytes)
>> No client guides found at ../phet-io-client-guides/projectile-motion/, no guides being built.
Fatal error: Perennial task failed:
AssertionError [ERR_ASSERTION] [ERR_ASSERTION]: full api expected
at module.exports (/data/share/phet/continuous-testing/ct-snapshots/1617722176576/chipper/js/grunt/copySupplementalPhetioFiles.js:294:5)
at module.exports (/data/share/phet/continuous-testing/ct-snapshots/1617722176576/chipper/js/grunt/buildRunnable.js:355:5)
at /data/share/phet/continuous-testing/ct-snapshots/1617722176576/chipper/js/grunt/Gruntfile.js:255:11
at wrap (/data/share/phet/continuous-testing/ct-snapshots/1617722176576/chipper/js/grunt/Gruntfile.js:74:7)

Full Error details:
AssertionError [ERR_ASSERTION]: full api expected

Browserslist: caniuse-lite is outdated. Please run:
npx browserslist@latest --update-db
Error [Error: Navigation failed because browser has disconnected!
at /data/share/phet/continuous-testing/ct-snapshots/1617722176576/chipper/node_modules/puppeteer/lib/cjs/puppeteer/common/LifecycleWatcher.js:51:147
at /data/share/phet/continuous-testing/ct-snapshots/1617722176576/chipper/node_modules/puppeteer/lib/cjs/vendor/mitt/src/index.js:51:62
at Array.map (<anonymous>:null:null)
at Object.emit (/data/share/phet/continuous-testing/ct-snapshots/1617722176576/chipper/node_modules/puppeteer/lib/cjs/vendor/mitt/src/index.js:51:43)
at CDPSession.emit (/data/share/phet/continuous-testing/ct-snapshots/1617722176576/chipper/node_modules/puppeteer/lib/cjs/puppeteer/common/EventEmitter.js:72:22)
at CDPSession._onClosed (/data/share/phet/continuous-testing/ct-snapshots/1617722176576/chipper/node_modules/puppeteer/lib/cjs/puppeteer/common/Connection.js:247:14)
at Connection._onClose (/data/share/phet/continuous-testing/ct-snapshots/1617722176576/chipper/node_modules/puppeteer/lib/cjs/puppeteer/common/Connection.js:128:21)
at WebSocket.<anonymous> (/data/share/phet/continuous-testing/ct-snapshots/1617722176576/chipper/node_modules/puppeteer/lib/cjs/puppeteer/node/NodeWebSocketTransport.js:17:30)
at WebSocket.onClose (/data/share/phet/continuous-testing/ct-snapshots/1617722176576/chipper/node_modules/puppeteer/node_modules/ws/lib/event-target.js:136:16)
at WebSocket.emit (events.js:315:20)
at WebSocket.emitClose (/data/share/phet/continuous-testing/ct-snapshots/1617722176576/chipper/node_modules/puppeteer/node_modules/ws/lib/websocket.js:198:10)
at Socket.socketOnClose (/data/share/phet/continuous-testing/ct-snapshots/1617722176576/chipper/node_modules/puppeteer/node_modules/ws/lib/websocket.js:886:15)
at Socket.emit (events.js:315:20)
at TCP.<anonymous> (net.js:673:12)
]
Snapshot from 4/6/2021, 9:16:16 AM
```

**Comment by jbphet** [comment]
I think this was assigned to me because I'm the responsible developer for this sim, but @zepumph has been doing the phet-io work, and this appears to be a phet-io issue.  Assigning to him.

**Comment by pixelzoom** [comment]
From Slack phet-io channel:

Chris Malley  10:20 AM
Any idea why CT is reporting this for ph-scale-basics and projectile-motion?

```
ph-scale-basics : build
Build failed with status code 1:
Running "report-media" task
Running "clean" task
Running "build" task
Building runnable repository (ph-scale-basics, brands: phet, phet-io)
Building brand: phet
>> Webpack build complete: 3861ms
>> Production minification complete: 23480ms (1435657 bytes)
>> Debug minification complete: 0ms (5391679 bytes)
Building brand: phet-io
>> Webpack build complete: 2622ms
>> Production minification complete: 19154ms (1457306 bytes)
>> Debug minification complete: 20771ms (1719213 bytes)
Fatal error: Perennial task failed:
AssertionError [ERR_ASSERTION] [ERR_ASSERTION]: full api expected
at module.exports (/data/share/phet/continuous-testing/ct-snapshots/1617702298432/chipper/js/grunt/copySupplementalPhetioFiles.js:294:5)
at module.exports (/data/share/phet/continuous-testing/ct-snapshots/1617702298432/chipper/js/grunt/buildRunnable.js:355:5)
at /data/share/phet/continuous-testing/ct-snapshots/1617702298432/chipper/js/grunt/Gruntfile.js:255:11
at wrap (/data/share/phet/continuous-testing/ct-snapshots/1617702298432/chipper/js/grunt/Gruntfile.js:74:7)
10:20
```

And what’s up with this error message? `AssertionError [ERR_ASSERTION] [ERR_ASSERTION]: full api expected`

Michael Kauzmann  10:21 AM
Most likely it is a failure in the puppeteer step that gets the api from the sim. Like in https://github.com/phetsims/chipper/issues/1022.
10:22
I added that assertion because this error used to be silently propagated to other parts of the PhET-iO build.

Chris Malley  10:22 AM
Is there something that should be catching that failure and providing a more intelligible error message?
10:23
Oh… So this is the result of catching the puppeteer failure? Can we improve the error message?  It tells me almost nothing about what’s wrong, and even less about what to do.
10:24
In the meantime…. Should I just ignore this?  Or is there something that needs to be corrected for these sims? (edited)

**Comment by pixelzoom** [comment]
Since this is happening for multiple sims and is failing in copySupplementalPhetioFiles.js, I'm transferring this issue from projectile-motion to chipper.
