### ISSUE TITLE
CT Time is 0but x is 2.737489296102892e-17

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/projectile-motion#311]
```
projectile-motion : fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1670235802704/projectile-motion/projectile-motion_en.html?continuousTest=%7B%22test%22%3A%5B%22projectile-motion%22%2C%22fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1670235802704%22%2C%22timestamp%22%3A1670237392458%7D&brand=phet&ea&fuzz&memoryLimit=1000
Query: brand=phet&ea&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: Time is 0but x is 2.737489296102892e-17
Error: Assertion failed: Time is 0but x is 2.737489296102892e-17
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1670235802704/assert/js/assert.js:28:13)
at assert (DataPoint.js:31:14)
at (Trajectory.js:316:17)
at step (ProjectileMotionModel.js:388:19)
at eventCallback (EventTimer.ts:111:11)
at step (ProjectileMotionModel.js:372:22)
at step (Sim.ts:426:21)
at apply (PhetioAction.ts:157:16)
at execute (Sim.ts:1026:30)
at stepSimulation (Sim.ts:1016:11)
id: Bayes Puppeteer
Snapshot from 12/5/2022, 3:23:22 AM

----------------------------------

projectile-motion : fuzz : unbuilt : assertSlow
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1670235802704/projectile-motion/projectile-motion_en.html?continuousTest=%7B%22test%22%3A%5B%22projectile-motion%22%2C%22fuzz%22%2C%22unbuilt%22%2C%22assertSlow%22%5D%2C%22snapshotName%22%3A%22snapshot-1670235802704%22%2C%22timestamp%22%3A1670243201246%7D&brand=phet&eall&fuzz&memoryLimit=1000
Query: brand=phet&eall&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: Time is 0but x is 0.7489571494014801
Error: Assertion failed: Time is 0but x is 0.7489571494014801
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1670235802704/assert/js/assert.js:28:13)
at assert (DataPoint.js:31:14)
at (Trajectory.js:316:17)
at step (ProjectileMotionModel.js:388:19)
at eventCallback (EventTimer.ts:111:11)
at step (ProjectileMotionModel.js:372:22)
at step (StatsModel.js:86:10)
at step (Sim.ts:426:21)
at apply (PhetioAction.ts:157:16)
at execute (Sim.ts:1026:30)
id: Bayes Puppeteer
Snapshot from 12/5/2022, 3:23:22 AM

----------------------------------

projectile-motion : multitouch-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1670235802704/projectile-motion/projectile-motion_en.html?continuousTest=%7B%22test%22%3A%5B%22projectile-motion%22%2C%22multitouch-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1670235802704%22%2C%22timestamp%22%3A1670237364199%7D&brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=false
Query: brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=false
Uncaught Error: Assertion failed: Time is 0but x is 0.3735730117844046
Error: Assertion failed: Time is 0but x is 0.3735730117844046
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1670235802704/assert/js/assert.js:28:13)
at assert (DataPoint.js:31:14)
at (Trajectory.js:316:17)
at step (ProjectileMotionModel.js:388:19)
at eventCallback (EventTimer.ts:111:11)
at step (ProjectileMotionModel.js:372:22)
at step (Sim.ts:426:21)
at apply (PhetioAction.ts:157:16)
at execute (Sim.ts:1026:30)
at stepSimulation (Sim.ts:1016:11)
id: Bayes Puppeteer
Snapshot from 12/5/2022, 3:23:22 AM

----------------------------------

projectile-motion : multitouch-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1670235802704/projectile-motion/projectile-motion_en.html?continuousTest=%7B%22test%22%3A%5B%22projectile-motion%22%2C%22multitouch-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1670235802704%22%2C%22timestamp%22%3A1670251714609%7D&brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=false
Query: brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=false
Uncaught Error: Assertion failed: Time is 0but x is -2.1519195363594475e-18
Error: Assertion failed: Time is 0but x is -2.1519195363594475e-18
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1670235802704/assert/js/assert.js:28:13)
at assert (DataPoint.js:31:14)
at (Trajectory.js:316:17)
at step (ProjectileMotionModel.js:388:19)
at eventCallback (EventTimer.ts:111:11)
at step (ProjectileMotionModel.js:372:22)
at step (StatsModel.js:86:10)
at step (Sim.ts:426:21)
at apply (PhetioAction.ts:157:16)
at execute (Sim.ts:1026:30)
id: Bayes Puppeteer
Snapshot from 12/5/2022, 3:23:22 AM

----------------------------------

projectile-motion : pan-and-zoom-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1670235802704/projectile-motion/projectile-motion_en.html?continuousTest=%7B%22test%22%3A%5B%22projectile-motion%22%2C%22pan-and-zoom-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1670235802704%22%2C%22timestamp%22%3A1670237931797%7D&brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=true
Query: brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=true
Uncaught Error: Assertion failed: Time is 0but x is 0.7493632658885995
Error: Assertion failed: Time is 0but x is 0.7493632658885995
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1670235802704/assert/js/assert.js:28:13)
at assert (DataPoint.js:31:14)
at (Trajectory.js:316:17)
at step (ProjectileMotionModel.js:388:19)
at eventCallback (EventTimer.ts:111:11)
at step (ProjectileMotionModel.js:372:22)
at step (Sim.ts:426:21)
at apply (PhetioAction.ts:157:16)
at execute (Sim.ts:1026:30)
at stepSimulation (Sim.ts:1016:11)
id: Bayes Puppeteer
Snapshot from 12/5/2022, 3:23:22 AM

----------------------------------

projectile-motion : pan-and-zoom-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1670235802704/projectile-motion/projectile-motion_en.html?continuousTest=%7B%22test%22%3A%5B%22projectile-motion%22%2C%22pan-and-zoom-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1670235802704%22%2C%22timestamp%22%3A1670253631070%7D&brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=true
Query: brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=true
Uncaught Error: Assertion failed: Time is 0but x is 4.2862637970157366e-17
Error: Assertion failed: Time is 0but x is 4.2862637970157366e-17
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1670235802704/assert/js/assert.js:28:13)
at assert (DataPoint.js:31:14)
at (Trajectory.js:316:17)
at step (ProjectileMotionModel.js:388:19)
at eventCallback (EventTimer.ts:111:11)
at step (ProjectileMotionModel.js:372:22)
at step (Sim.ts:426:21)
at apply (PhetioAction.ts:157:16)
at execute (Sim.ts:1026:30)
at stepSimulation (Sim.ts:1016:11)
id: Bayes Puppeteer
Snapshot from 12/5/2022, 3:23:22 AM

----------------------------------

projectile-motion : phet-io-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1670235802704/projectile-motion/projectile-motion_en.html?continuousTest=%7B%22test%22%3A%5B%22projectile-motion%22%2C%22phet-io-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1670235802704%22%2C%22timestamp%22%3A1670250907191%7D&ea&brand=phet-io&phetioStandalone&fuzz&memoryLimit=1000
Query: ea&brand=phet-io&phetioStandalone&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: Time is 0but x is 2.737489296102892e-17
Error: Assertion failed: Time is 0but x is 2.737489296102892e-17
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1670235802704/assert/js/assert.js:28:13)
at assert (DataPoint.js:31:14)
at (Trajectory.js:316:17)
at step (ProjectileMotionModel.js:388:19)
at eventCallback (EventTimer.ts:111:11)
at step (ProjectileMotionModel.js:372:22)
at step (Sim.ts:426:21)
at apply (PhetioAction.ts:157:16)
at execute (Sim.ts:1026:30)
at stepSimulation (Sim.ts:1016:11)
id: Bayes Puppeteer
Snapshot from 12/5/2022, 3:23:22 AM

----------------------------------

projectile-motion : xss-fuzz
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1670235802704/projectile-motion/projectile-motion_en.html?continuousTest=%7B%22test%22%3A%5B%22projectile-motion%22%2C%22xss-fuzz%22%5D%2C%22snapshotName%22%3A%22snapshot-1670235802704%22%2C%22timestamp%22%3A1670253496270%7D&brand=phet&ea&fuzz&stringTest=xss&memoryLimit=1000
Query: brand=phet&ea&fuzz&stringTest=xss&memoryLimit=1000
Uncaught Error: Assertion failed: Time is 0but x is 2.737489296102892e-17
Error: Assertion failed: Time is 0but x is 2.737489296102892e-17
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1670235802704/assert/js/assert.js:28:13)
at assert (DataPoint.js:31:14)
at (Trajectory.js:316:17)
at step (ProjectileMotionModel.js:388:19)
at eventCallback (EventTimer.ts:111:11)
at step (ProjectileMotionModel.js:372:22)
at step (Sim.ts:426:21)
at apply (PhetioAction.ts:157:16)
at execute (Sim.ts:1026:30)
at stepSimulation (Sim.ts:1016:11)
id: Bayes Puppeteer
Snapshot from 12/5/2022, 3:23:22 AM
```

**Comment by zepumph** [comment]
I thought this was fixed on master by @matthew-blackman but I can't find the commit.
