### ISSUE TITLE
CT: Emitted unexpected number of args. Expected: 0 and received 1

### ISSUE THREAD

**Issue by jbphet** [phetsims/projectile-motion#318]
The CT readout for Projectile Motion is looking pretty red:

![image](https://user-images.githubusercontent.com/3082831/208493882-31100b52-1b45-4a0a-92c9-6a1fbc5e44c7.png)

It's failing a number of different tests, but they all seem to have the same message.  It is:

```projectile-motion : fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1671456500298/projectile-motion/projectile-motion_en.html?continuousTest=%7B%22test%22%3A%5B%22projectile-motion%22%2C%22fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1671456500298%22%2C%22timestamp%22%3A1671458923847%7D&brand=phet&ea&fuzz&memoryLimit=1000
Query: brand=phet&ea&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: Emitted unexpected number of args. Expected: 0 and received 1
Error: Assertion failed: Emitted unexpected number of args. Expected: 0 and received 1
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1671456500298/assert/js/assert.js:28:13)
at assert (PhetioDataHandler.ts:161:14)
at validateArguments (Emitter.ts:117:19)
at emit (ProjectileMotionModel.ts:353:28)
at eventCallback (EventTimer.ts:111:11)
at step (ProjectileMotionModel.ts:339:22)
at step (Sim.ts:427:21)
at apply (PhetioAction.ts:157:16)
at execute (Sim.ts:1030:30)
at stepSimulation (Sim.ts:1020:11)
id: Bayes Puppeteer
Snapshot from 12/19/2022, 6:28:20 AM
```

**Comment by jbphet** [comment]
@matthew-blackman and I looked at this together, and could see that it has something to do with emitters and phet-io validation.  He thought it might have something to do with the TypeScript conversion that he's working on.  It's apparently about 80% done, so he's going to finish the conversion and see if it fixes this issue.
