### ISSUE TITLE
CT required tandems must be supplied

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/projectile-motion#319]
```
projectile-motion : phet-io-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1673352571583/projectile-motion/projectile-motion_en.html?continuousTest=%7B%22test%22%3A%5B%22projectile-motion%22%2C%22phet-io-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1673352571583%22%2C%22timestamp%22%3A1673354716974%7D&ea&brand=phet-io&phetioStandalone&fuzz&memoryLimit=1000
Query: ea&brand=phet-io&phetioStandalone&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: required tandems must be supplied
Error: Assertion failed: required tandems must be supplied
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1673352571583/assert/js/assert.js:28:13)
at assert (PhetioObject.ts:200:16)
at initializePhetioObject (Node.ts:6320:10)
at initializePhetioObject (Node.ts:6310:9)
at mutate (Node.ts:830:11)
at (ScreenView.ts:97:4)
at (ProjectileMotionScreenView.ts:114:4)
at (IntroScreenView.js:49:4)
at (IntroScreen.ts:38:15)
at createView (Screen.ts:304:22)
id: Bayes Puppeteer
Snapshot from 1/10/2023, 5:09:31 AM
```

**Comment by jbphet** [comment]
The commit 765b991b7b746bdeb73a189fa5667b9a2e14a4d3 seems implicated in this CT issue, specifically the changes to `ProjectileMotionScreenView.ts`, since it was passing a tandem to its super, and now it isn't.  @zepumph - Can you please have a look, since you made the change?

**Comment by zepumph** [comment]
Yes thanks. Sorry for the trouble. While I was here I brought things up to the standard way we pass tandem through in screen views.
